Repository wpi-25/bot, pull requests merged in 2021-01, with the labels that each got.

#20 Disallow commands increasing XP/count and lock level commands to certain channels
  Types.ts
  config.json.example
  triggers/commands/levels.ts
  triggers/commands/rank.ts
  triggers/triggers/levels.ts
  util/commands.ts
  util/text.ts
Labels: enhancement

#21 Split index.ts apart into helper files
  helpers/lifecycle.ts
  helpers/members.ts
  helpers/messageHandler.ts
  helpers/modules.ts
  helpers/reactionHandler.ts
  helpers/vc.ts
  index.ts
  triggers/commands/help.ts
  triggers/commands/install.ts
  triggers/commands/levels.ts
  triggers/commands/reload.ts
  triggers/commands/restart.ts
  triggers/commands/shutdown.ts
  triggers/commands/uninstall.ts
  triggers/commands/update.ts
  util/commands.ts
  util/levels.ts
Labels: enhancement, refactor

#24 Switch to log-based levels
  .dcignore
  .gitignore
  Types.ts
  triggers/commands/rank.ts
  util/levels.ts
Labels: enhancement, refactor

#29 Add hex code and TikTok embed triggers
  helpers/messageHandler.ts
  triggers/triggers/hex.ts
  triggers/triggers/tiktok.ts
Labels: enhancement

#30 Fix update command
  triggers/commands/update.ts
Labels: bug, refactor

#34 Level roles
  Types.ts
  triggers/triggers/levels.ts
  util/levels.ts
Labels: enhancement

#36 Fix Loose RegEx
  triggers/triggers/tiktok.ts
Labels: bug

#37 Add number formatting and even out string lengths
  triggers/commands/levels.ts
Labels: enhancement

#39 Change the name displayed on the leaderboard to nicknames instead of …
  triggers/commands/levels.ts
Labels: enhancement
